#!/usr/bin/env bash
# Install and configure HAProxy on lb-01 server

# Install HAProxy
sudo apt update
sudo apt install -y haproxy

# Configure HAProxy
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOF
global
        log /dev/log local0
        log /dev/log local1 notice
        chroot /var/lib/haproxy
        stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
        stats timeout 30s
        user haproxy
        group haproxy
        daemon

defaults
        log global
        mode http
        option httplog
        option dontlognull
        timeout connect 5000
        timeout client  50000
        timeout server  50000

frontend http_front
        bind *:80
        stats uri /haproxy?stats
        default_backend http_back

backend http_back
        balance roundrobin
        option http-server-close
        server 471042-web-01 100.25.212.93:80 check
        server 471042-web-02 18.206.206.112 check
EOF

# Restart HAProxy
sudo systemctl restart haproxy

# Enable HAProxy init script
sudo systemctl enable haproxy

echo "HAProxy installed and configured successfully."
