#!/usr/bin/env bash
# This code displays the part of the name after the first dash,
#    It only displays the part of the name after the first dash.

list=$(ls)
for i in $list; do
	echo "$i" | cut -d '-' -f2
done
